### ISSUE TITLE
Mini-GitHub tutorial

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/ai_research#7]
This is to introduce the git workflow (creating issues, branches and Pull Requests). Would you be happy to convene @kstathou? I would attend too.

**Comment by kstathou** [comment]
Sounds good, I will schedule something for next Tuesday.

**Comment by daniel-hain** [comment]
Great! Thanks so much. If possible after 5.30pm DK time. Sorry, but Mon-Wed full day statistics exams....
